# -*- coding: utf-8 -*-
"""Week7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c8Z6BOH5XuC7hzMDEKlKBhBufDknMrnY
"""

import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()

df = pd.read_csv(next(iter(uploaded)))

print("First 5 rows:")
display(df.head())

categorical_features = [
    'gender',
    'race/ethnicity',
    'parental level of education',
    'lunch',
    'test preparation course'
]

for col in categorical_features:
    df[col] = df[col].astype(str).str.strip().str.title()

score_columns = [
    'math score',
    'reading score',
    'writing score'
]

for col in score_columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')

statistics = df[score_columns].describe()

print("\nStatistical Measures:")
display(statistics)

print("\nMedian:")
print(df[score_columns].median())

df['Total Marks'] = df[score_columns].sum(axis=1)

df['Percentage'] = (df['Total Marks'] / 300) * 100

print("\nExtreme Performance Outliers:")

for col in score_columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower_limit) | (df[col] > upper_limit)]

    print("\n", col)
    print("Lower Limit:", lower_limit)
    print("Upper Limit:", upper_limit)
    print("Number of Outliers:", len(outliers))

print("\nFinal Dataset:")
display(df.head(10))