# -*- coding: utf-8 -*-
"""week8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEwf4JLLvB3TYihiMJuuAdSzYjbYJNsI
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

df = pd.read_csv(next(iter(uploaded)))

print("Dataset:")
display(df.head())

print("\nColumn Names:")
print(df.columns.tolist())

avg_scores = df.groupby(
    ['parental level of education', 'lunch']
)[['math score', 'reading score', 'writing score']].mean()

avg_scores.plot(
    kind='bar',
    figsize=(14, 7)
)

plt.title('Average Test Scores by Parental Education and Lunch Type')
plt.xlabel('Parental Level of Education and Lunch')
plt.ylabel('Average Score')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Subject')
plt.tight_layout()
plt.show()

plt.figure(figsize=(12, 6))

sns.boxplot(
    data=df,
    x='test preparation course',
    y='math score'
)

plt.title('Math Score Variance by Test Preparation Course')
plt.xlabel('Test Preparation Course')
plt.ylabel('Math Score')
plt.show()


plt.figure(figsize=(12, 6))
sns.boxplot(
    data=df,
    x='test preparation course',
    y='reading score'
)

plt.title('Reading Score Variance by Test Preparation Course')
plt.xlabel('Test Preparation Course')
plt.ylabel('Reading Score')
plt.show()


plt.figure(figsize=(12, 6))
sns.boxplot(
    data=df,
    x='test preparation course',
    y='writing score'
)

plt.title('Writing Score Variance by Test Preparation Course')
plt.xlabel('Test Preparation Course')
plt.ylabel('Writing Score')
plt.show()

plt.figure(figsize=(7, 5))

sns.scatterplot(
    data=df,
    x='math score',
    y='reading score'
)

plt.title('Math Score vs Reading Score')
plt.xlabel('Math Score')
plt.ylabel('Reading Score')
plt.show()

plt.figure(figsize=(7, 5))

sns.scatterplot(
    data=df,
    x='math score',
    y='writing score'
)

plt.title('Math Score vs Writing Score')
plt.xlabel('Math Score')
plt.ylabel('Writing Score')
plt.show()

plt.figure(figsize=(7, 5))

sns.scatterplot(
    data=df,
    x='reading score',
    y='writing score'
)

plt.title('Reading Score vs Writing Score')
plt.xlabel('Reading Score')
plt.ylabel('Writing Score')
plt.show()

score_columns = [
    'math score',
    'reading score',
    'writing score'
]

correlation = df[score_columns].corr()

plt.figure(figsize=(8, 6))

sns.heatmap(
    correlation,
    annot=True,
    cmap='coolwarm',
    fmt='.2f'
)

plt.title('Correlation Heatmap of Student Scores')
plt.show()

print("Educational Insights")
print("--------------------")

print("\nAverage Scores:")
print(df[score_columns].mean())

print("\nAverage Scores by Test Preparation:")
print(
    df.groupby('test preparation course')[score_columns].mean()
)

print("\nAverage Scores by Lunch Type:")
print(
    df.groupby('lunch')[score_columns].mean()
)
print("\nAverage Scores by Parental Education:")
print(
    df.groupby('parental level of education')[score_columns].mean()
)